### ISSUE TITLE
Share your home dashboard?

### ISSUE THREAD

**Issue by CumpsD** [lukevink/home-assistant-buienradar-forecast-card#18]
Any chance you can share the config for this layout?

https://github.com/lukevink/lovelace-buien-rain-card/blob/master/buien-card-screenshot2.png

**Comment by craggyh** [comment]
Yes, I too would like the code for this layout. Specifically the section for rain forecast, that’s very neat. 
mud it possible to use this layout with another weather provider like openweathermap for rain prediction?

**Comment by CumpsD** [comment]
@lukevink

**Comment by craggyh** [comment]
Never mind, I found the weather card on HACS that looks pretty similar and works with my weather integration - https://github.com/bramkragten/weather-card

**Comment by CumpsD** [comment]
Thanks, that looks good!
